
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { useState, useEffect } from "react";
import puzzleImage from "@/assets/puzzle_matrix.png";

const PUZZLE_PIECES = [
    {
        id: 'top-left',
        title: "Productization",
        color: "bg-[#4a86ba]",
        content: [
            "Standardized design prototypes.",
            "Repeatable kit of parts.",
            "Design for Manufacturing & Assembly (DfMA).",
            "Optimized for construction savings."
        ]
    },
    {
        id: 'top-right',
        title: "Assembly Detail",
        color: "bg-[#7db063]",
        content: [
            "300+ assemblies & sub-assemblies.",
            "Code compliant & localized.",
            "Detailed scope by MasterFormat division.",
            "Simplified GC scope discussion."
        ]
    },
    {
        id: 'bottom-left',
        title: "Bill of Quantity Engine",
        color: "bg-[#e0a84d]",
        content: [
            "Automatically generated by building geometry.",
            "Algorithms to calculate assembly quantities.",
            "Labor & material update based on inputs.",
            "Guesswork replaced by actual dimensions."
        ]
    },
    {
        id: 'bottom-right',
        title: "Cost Database",
        color: "bg-[#4a5a6a]",
        content: [
            "Standardized labor and material data.",
            "Regional GC inputs.",
            "Frequent updates based on actual project data.",
            "Accurate basis for bid negotiation."
        ]
    }
];

interface MethodologyDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
}

function useMediaQuery(query: string) {
    const [matches, setMatches] = useState(false);

    useEffect(() => {
        const media = window.matchMedia(query);
        if (media.matches !== matches) {
            setMatches(media.matches);
        }
        const listener = () => setMatches(media.matches);
        media.addEventListener("change", listener);
        return () => media.removeEventListener("change", listener);
    }, [matches, query]);

    return matches;
}

export function MethodologyDialog({ open, onOpenChange }: MethodologyDialogProps) {
    const [activePiece, setActivePiece] = useState<string | null>(null);

    // Auto-open "Productization" when dialog opens
    useEffect(() => {
        if (open) {
            setActivePiece('top-left');
        } else {
            setActivePiece(null);
        }
    }, [open]);

    const isDesktop = useMediaQuery("(min-width: 768px)");

    const handlePieceClick = (id: string) => {
        setActivePiece(activePiece === id ? null : id);
    };

    const Content = () => (
        <div className="flex-1 overflow-y-auto min-h-0 flex flex-col items-center pb-20 md:pb-0">
            {/* 1. Puzzle Matrix Section */}

            {/* Mobile: Stacked Cards View */}
            <div className="md:hidden w-full space-y-4 pt-4">
                {PUZZLE_PIECES.map((piece) => (
                    <div key={piece.id} className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
                        <div className={`${piece.color} p-2 text-white font-bold text-base`}>
                            {piece.title}
                        </div>
                        <div className="p-3 bg-gray-50">
                            <ul className="space-y-1 text-sm md:text-base text-gray-700 list-disc pl-4 leading-relaxed">
                                {piece.content.map((point, i) => (
                                    <li key={i}>{point}</li>
                                ))}
                            </ul>
                        </div>
                    </div>
                ))}
            </div>

            {/* Desktop: Interactive Matrix View */}
            <div className="hidden md:block relative aspect-square max-h-[60vh] w-auto md:max-h-none md:w-full md:max-w-[500px] my-2">
                <img
                    src={puzzleImage}
                    alt="RaaP Methodology Matrix"
                    className="h-full w-auto object-contain"
                />

                {/* Clickable Overlay Zones - 2x2 Grid */}
                <div className="absolute inset-0 grid grid-cols-2 grid-rows-2">
                    {PUZZLE_PIECES.map((piece) => (
                        <div
                            key={piece.id}
                            onClick={() => handlePieceClick(piece.id)}
                            className={`
            cursor-pointer transition-colors duration-200
            hover:bg-white/5 rounded-xl
            ${activePiece === piece.id ? 'ring-inset ring-4 ring-white/50' : ''}
          `}
                        />
                    ))}
                </div>

                {/* Info Overlay Box - Shows when a piece is active */}
                {activePiece && (
                    <div
                        className="absolute inset-0 flex items-center justify-center p-4 md:p-8 z-10 animate-in fade-in duration-300"
                        onClick={() => setActivePiece(null)}
                    >
                        <div
                            className="bg-white/95 backdrop-blur-md rounded-xl shadow-2xl p-4 md:p-8 max-w-md w-full border-l-8 transform scale-105 transition-all overflow-y-auto max-h-full"
                            style={{
                                borderLeftColor: PUZZLE_PIECES.find(p => p.id === activePiece)?.color === 'bg-[#4a86ba]' ? '#4a86ba' :
                                    PUZZLE_PIECES.find(p => p.id === activePiece)?.color === 'bg-[#7db063]' ? '#7db063' :
                                        PUZZLE_PIECES.find(p => p.id === activePiece)?.color === 'bg-[#e0a84d]' ? '#e0a84d' : '#4a5a6a'
                            }}
                            onClick={(e) => e.stopPropagation()}
                        >
                            <h3 className="text-xl md:text-2xl font-bold mb-4 md:mb-6 text-gray-900 border-b pb-2 md:pb-4">
                                {PUZZLE_PIECES.find(p => p.id === activePiece)?.title}
                            </h3>
                            <ul className="space-y-2 md:space-y-3 text-sm md:text-base text-gray-700 list-disc pl-5 leading-relaxed">
                                {(PUZZLE_PIECES.find(p => p.id === activePiece)?.content || []).map((point, i) => (
                                    <li key={i}>{point}</li>
                                ))}
                            </ul>
                            <button
                                onClick={() => setActivePiece(null)}
                                className="mt-4 md:mt-8 w-full py-2 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-lg text-xs font-bold tracking-widest uppercase transition-colors"
                            >
                                Close Details
                            </button>
                        </div>
                    </div>
                )}
            </div>

            {/* 2. Key Outcomes Section */}
            {/* Reduced max-width (1000px -> 800px) to shrink the boxes as requested */}
            <div className="space-y-6 md:space-y-12 w-full max-w-[800px] mx-auto pb-8 pt-4">
                <div className="text-center space-y-4 md:space-y-8">
                    <p className="text-sm md:text-lg text-gray-700 italic max-w-2xl mx-auto leading-relaxed px-4">
                        RaaP doesn’t rely on any single technique — cost certainty emerges from how these four components work together.
                    </p>
                    <h2 className="text-2xl md:text-3xl font-extrabold text-[#003f87] tracking-tight relative inline-block">
                        Key Outcomes
                        <span className="absolute -bottom-2 md:-bottom-3 left-1/2 -translate-x-1/2 w-8 md:w-12 h-1 bg-[#f0ab00] rounded-full"></span>
                    </h2>
                </div>

                <div className="grid md:grid-cols-2 gap-4 md:gap-8 px-4">
                    <div className="bg-white p-5 md:p-8 rounded-2xl shadow-lg border border-gray-100 hover:shadow-xl transition-shadow duration-300">
                        <h3 className="text-base md:text-xl font-bold text-[#003f87] border-b-2 border-gray-100 pb-2 md:pb-4 mb-2 md:mb-4">
                            Early construction cost certainty
                        </h3>
                        <ul className="space-y-2 md:space-y-3 text-sm md:text-base text-gray-600 list-disc pl-4 marker:text-blue-500 leading-relaxed">
                            <li>Estimates based on design assemblies rather than GC guesses.</li>
                            <li>Supports more accurate calculation of site value.</li>
                            <li>Better understanding of mix & dimension tradeoffs.</li>
                            <li>Avoid estimation errors due to non-linear cost drivers.</li>
                        </ul>
                    </div>

                    <div className="bg-white p-5 md:p-8 rounded-2xl shadow-lg border border-gray-100 hover:shadow-xl transition-shadow duration-300">
                        <h3 className="text-base md:text-xl font-bold text-[#003f87] border-b-2 border-gray-100 pb-2 md:pb-4 mb-2 md:mb-4">
                            Lower overall construction costs
                        </h3>
                        <ul className="space-y-2 md:space-y-3 text-sm md:text-base text-gray-600 list-disc pl-4 marker:text-green-500 leading-relaxed">
                            <li>Reduce design & soft fees.</li>
                            <li>Reduce contingencies & margin stacking.</li>
                            <li>Negotiate bids based on an engineered view of costs.</li>
                            <li>Pre-purchase materials to combat rising prices & tariffs.</li>
                        </ul>
                    </div>
                </div>

                {/* Enhanced centering: w-fit + mx-auto ensures it centers perfectly below the boxes */}
                {/* Robust centering using text-center on container and inline-block on element */}
                <div className="w-full text-center">
                    <p className="inline-block text-xs md:text-sm text-[#003f87] font-medium bg-blue-50/50 py-2 md:py-3 px-4 md:px-6 rounded-full border border-blue-100">
                        ℹ️ Click on the divisions in the cost breakdown to view the assembly detail.
                    </p>
                </div>
            </div>
        </div>
    );

    return (
        <>
            {/* Mobile: Custom Full Screen View (No Dialog, No X) */}
            {open && (
                <div className="md:hidden fixed inset-0 z-40 bg-white overflow-y-auto animate-in slide-in-from-bottom-5 duration-300 pt-20">
                    <div className="p-4">
                        <h2 className="text-xl font-extrabold text-[#003f87] text-center mb-1 whitespace-normal leading-tight">
                            How RaaP delivers early cost certainty.<br /> Why it lowers construction costs.
                        </h2>
                        <Content />
                    </div>
                </div>
            )}

            {/* Desktop: Standard Dialog - Only render if desktop to avoid overlay on mobile */}
            <Dialog open={open && isDesktop} onOpenChange={onOpenChange}>
                <DialogContent className="hidden md:flex max-w-[95vw] w-fit max-h-[95vh] overflow-hidden flex-col p-4">
                    <DialogHeader className="flex-shrink-0">
                        <DialogTitle className="text-3xl font-extrabold text-[#003f87] text-center mb-1 whitespace-nowrap leading-tight">
                            How RaaP delivers early cost certainty. Why it lowers construction costs.
                        </DialogTitle>
                    </DialogHeader>
                    <Content />
                </DialogContent>
            </Dialog>
        </>
    );
}

